/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.ConnectionFactory;
import java.sql.Connection;
import java.text.DateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Master
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopmenu = new javax.swing.JDesktopPane();
        btnCli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEquipa = new javax.swing.JButton();
        btnTServ = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnForn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCliRel = new javax.swing.JButton();
        btnTContRel = new javax.swing.JButton();
        btnTServRel = new javax.swing.JButton();
        btnAdminRel = new javax.swing.JButton();
        btnFornRel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnOrdAtend = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuCadAdm = new javax.swing.JMenuItem();
        jMenuCadCid = new javax.swing.JMenuItem();
        jMenuCadCli = new javax.swing.JMenuItem();
        jMenuCadCompra = new javax.swing.JMenuItem();
        jMenuCadContrato = new javax.swing.JMenuItem();
        jMenuCadEquip = new javax.swing.JMenuItem();
        jMenuCadEstado = new javax.swing.JMenuItem();
        jMenuCadForn = new javax.swing.JMenuItem();
        jMenuCadOs = new javax.swing.JMenuItem();
        jMenuCadOsAtendida = new javax.swing.JMenuItem();
        jMenuCadTipoServ = new javax.swing.JMenuItem();
        jMenuCadUsuario = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuRelServ = new javax.swing.JMenuItem();
        jMenuRelEstCid = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuAjuSobre = new javax.swing.JMenuItem();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuOpSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE ORDEM DE SERVIÇOS");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/LogoSys270x250.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btnCli.setText("Cliente");
        btnCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de Controle de Ordem de Serviço");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cadastros");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Operações com Ordem de Serviço");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Relatórios");

        btnEquipa.setText("Equipamento");
        btnEquipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipaActionPerformed(evt);
            }
        });

        btnTServ.setText("Ord. Serv.");
        btnTServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTServActionPerformed(evt);
            }
        });

        btnAdmin.setText("Administradora");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnForn.setText("Fornecedor");
        btnForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("De Cadastro");

        btnCliRel.setText("Cliente");

        btnTContRel.setText("Contratos");

        btnTServRel.setText("Serviços");

        btnAdminRel.setText("Administradoras");

        btnFornRel.setText("Fornecedores");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gerenciais");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnOrdAtend.setText("Ord.Atend.");
        btnOrdAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdAtendActionPerformed(evt);
            }
        });

        jButton1.setText("Compra");

        jLabel8.setFont(new java.awt.Font("Vivaldi", 2, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Enterdata Sistemas & Projetos");

        jDesktopmenu.setLayer(btnCli, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(btnEquipa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(btnTServ, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(btnAdmin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(btnForn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(btnCliRel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(btnTContRel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(btnTServRel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(btnAdminRel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(btnFornRel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(btnOrdAtend, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopmenu.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopmenuLayout = new javax.swing.GroupLayout(jDesktopmenu);
        jDesktopmenu.setLayout(jDesktopmenuLayout);
        jDesktopmenuLayout.setHorizontalGroup(
            jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopmenuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopmenuLayout.createSequentialGroup()
                        .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEquipa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnForn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopmenuLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(271, 271, 271))
                            .addGroup(jDesktopmenuLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jDesktopmenuLayout.createSequentialGroup()
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnOrdAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnTServ, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTContRel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCliRel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAdminRel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTServRel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnFornRel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jDesktopmenuLayout.createSequentialGroup()
                        .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopmenuLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopmenuLayout.createSequentialGroup()
                                        .addGap(183, 183, 183)
                                        .addComponent(jLabel4)
                                        .addGap(199, 199, 199)
                                        .addComponent(jLabel5))
                                    .addGroup(jDesktopmenuLayout.createSequentialGroup()
                                        .addGap(269, 269, 269)
                                        .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(102, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopmenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jDesktopmenuLayout.setVerticalGroup(
            jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopmenuLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopmenuLayout.createSequentialGroup()
                        .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopmenuLayout.createSequentialGroup()
                                .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAdmin)
                                    .addComponent(btnTServ))
                                .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopmenuLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCli)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEquipa)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnForn))
                                    .addGroup(jDesktopmenuLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnOrdAtend))))
                            .addGroup(jDesktopmenuLayout.createSequentialGroup()
                                .addComponent(btnCliRel)
                                .addGap(18, 18, 18)
                                .addComponent(btnTContRel)
                                .addGap(18, 18, 18)
                                .addComponent(btnTServRel)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdminRel)
                                .addGap(18, 18, 18)
                                .addComponent(btnFornRel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopmenuLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jDesktopmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2))
                        .addGap(74, 74, 74))))
        );

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setText("Usuário");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblData.setText("Data");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogoSys270x250.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jMenuCadastro.setText("Cadastro");

        jMenuCadAdm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadAdm.setText("Administradora");
        jMenuCadAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadAdmActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadAdm);

        jMenuCadCid.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadCid.setText("Cidade");
        jMenuCadCid.setEnabled(false);
        jMenuCadCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadCidActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadCid);

        jMenuCadCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadCli.setText("Cliente");
        jMenuCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadCliActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadCli);

        jMenuCadCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadCompra.setText("Compra");
        jMenuCadastro.add(jMenuCadCompra);

        jMenuCadContrato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadContrato.setText("Contrato");
        jMenuCadContrato.setEnabled(false);
        jMenuCadContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadContratoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadContrato);

        jMenuCadEquip.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadEquip.setText("Equipamento");
        jMenuCadEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadEquipActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadEquip);

        jMenuCadEstado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadEstado.setText("Estado");
        jMenuCadEstado.setEnabled(false);
        jMenuCadEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadEstadoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadEstado);

        jMenuCadForn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadForn.setText("Fornecedor");
        jMenuCadForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadFornActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadForn);

        jMenuCadOs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadOs.setText("Os");
        jMenuCadOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadOsActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadOs);

        jMenuCadOsAtendida.setText("Os Atendida");
        jMenuCadOsAtendida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadOsAtendidaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadOsAtendida);

        jMenuCadTipoServ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadTipoServ.setText("Tipo de Serviço");
        jMenuCadTipoServ.setEnabled(false);
        jMenuCadTipoServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadTipoServActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadTipoServ);

        jMenuCadUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadUsuario.setText("Usuário");
        jMenuCadUsuario.setEnabled(false);
        jMenuCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadUsuario);

        jMenu.add(jMenuCadastro);

        jMenuRelatorio.setText("Relatórios");
        jMenuRelatorio.setEnabled(false);

        jMenuRelServ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuRelServ.setText("Serviços");
        jMenuRelatorio.add(jMenuRelServ);

        jMenuRelEstCid.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuRelEstCid.setText("EstadosXCidades");
        jMenuRelEstCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelEstCidActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuRelEstCid);

        jMenu.add(jMenuRelatorio);

        jMenuAjuda.setText("Ajuda");

        jMenuAjuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        jMenuAjuSobre.setText("Sobre");
        jMenuAjuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAjuSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuAjuSobre);

        jMenu.add(jMenuAjuda);

        jMenuOpcoes.setText("Opções");

        jMenuOpSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.ALT_MASK));
        jMenuOpSair.setText("Sair");
        jMenuOpSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpSairActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuOpSair);

        jMenu.add(jMenuOpcoes);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDesktopmenu)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1398, 707));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        // as linha abaixo atribue ao labal lbldata a data atual obtida do sistema
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
        
    }//GEN-LAST:event_formWindowActivated

    private void jMenuOpSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpSairActionPerformed
        // TODO add your handling code here:
        //exibe uma caixa de dialogo yes or now
        int sair = JOptionPane.showConfirmDialog(null, "Deseja mesmo sair do sistema???","Atenção",JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuOpSairActionPerformed

    private void jMenuAjuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAjuSobreActionPerformed
        // chama a tela sobre
        FormTelaSobre telasobre = new FormTelaSobre();
        telasobre.setVisible(true);
    }//GEN-LAST:event_jMenuAjuSobreActionPerformed

    private void jMenuCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadUsuarioActionPerformed
        // Abre o formulário de usuarios
        FormUsuario usuario = new FormUsuario();
        usuario.setVisible(true);
        
    }//GEN-LAST:event_jMenuCadUsuarioActionPerformed

    private void jMenuCadAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadAdmActionPerformed
        // Abre o formulário Administradora
        FormAdministradora adm = new FormAdministradora();
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuCadAdmActionPerformed

    private void jMenuCadCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadCidActionPerformed
        // Abre o formulário Cidade
        FormCidade cid = new FormCidade();
        cid.setVisible(true);
    }//GEN-LAST:event_jMenuCadCidActionPerformed

    private void jMenuCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadCliActionPerformed
        // Abre o formulário Cliente
        FormCliente cli = new FormCliente();
        cli.setVisible(true);
    }//GEN-LAST:event_jMenuCadCliActionPerformed

    private void jMenuCadContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadContratoActionPerformed
        // Abre o formulário Contrato
        FormContrato cont = new FormContrato();
        cont.setVisible(true);
    }//GEN-LAST:event_jMenuCadContratoActionPerformed

    private void jMenuCadEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadEquipActionPerformed
        // Abre o formulário Equipamento
        FormEquipamento eq = new FormEquipamento();
        eq.setVisible(true);
    }//GEN-LAST:event_jMenuCadEquipActionPerformed

    private void jMenuCadEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadEstadoActionPerformed
        // Abre o formulário Estado
        FormEstado est = new FormEstado();
        est.setVisible(true);
    }//GEN-LAST:event_jMenuCadEstadoActionPerformed

    private void jMenuCadFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadFornActionPerformed
        // Abre o formulário Fornecedor
        FormFornecedor forn = new FormFornecedor();
        forn.setVisible(true);
    }//GEN-LAST:event_jMenuCadFornActionPerformed

    private void jMenuCadOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadOsActionPerformed
        // Abre o formulário Os
        FormOs os = new FormOs();
        os.setVisible(true);
    }//GEN-LAST:event_jMenuCadOsActionPerformed

    private void jMenuCadOsAtendidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadOsAtendidaActionPerformed
        // Abre o formulário de Os atendida:
        FormOsAtendida osa = new FormOsAtendida();
        osa.setVisible(true);
    }//GEN-LAST:event_jMenuCadOsAtendidaActionPerformed

    private void jMenuCadTipoServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadTipoServActionPerformed
        // Abre o formulário de tipo de serviço:
        FormTipoServ tserv = new FormTipoServ();
        tserv.setVisible(true);
    }//GEN-LAST:event_jMenuCadTipoServActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
         FormAdministradora adm = new FormAdministradora();
        adm.setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornActionPerformed
        // TODO add your handling code here:
        FormFornecedor forn = new FormFornecedor();
        forn.setVisible(true);
    }//GEN-LAST:event_btnFornActionPerformed

    private void btnCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliActionPerformed
        // TODO add your handling code here:
        FormCliente cliente = new FormCliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_btnCliActionPerformed

    private void btnEquipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipaActionPerformed
        // TODO add your handling code here:
        FormEquipamento equipamento = new FormEquipamento();
        equipamento.setVisible(true);
    }//GEN-LAST:event_btnEquipaActionPerformed

    private void btnTServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTServActionPerformed
        // TODO add your handling code here:
        FormOs os = new FormOs();
        os.setVisible(true);
    }//GEN-LAST:event_btnTServActionPerformed

    private void btnOrdAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdAtendActionPerformed
        // TODO add your handling code here:
        FormOsAtendida ordatendida = new FormOsAtendida();
        ordatendida.setVisible(true);
    }//GEN-LAST:event_btnOrdAtendActionPerformed

    private void jMenuRelEstCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelEstCidActionPerformed
        // TODO add your handling code here:
        
        try {
        Connection con = ConnectionFactory.getConnection();
        
        JasperReport report = null;
        String path = "src\\reports\\Cidades.jasper";
        
        Map parametro = new HashMap();
        
        //o numero de parametro se refere ao id do Rio de janeiro e este valor pode ser obtido de um combo ou entrada por teclado
        parametro.put("idestado", 19);
        
            report = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(report, parametro, con);
            
            JasperViewer view = new JasperViewer(jprint, false);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(FormMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jMenuRelEstCidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAdminRel;
    private javax.swing.JButton btnCli;
    private javax.swing.JButton btnCliRel;
    private javax.swing.JButton btnEquipa;
    private javax.swing.JButton btnForn;
    private javax.swing.JButton btnFornRel;
    private javax.swing.JButton btnOrdAtend;
    private javax.swing.JButton btnTContRel;
    private javax.swing.JButton btnTServ;
    private javax.swing.JButton btnTServRel;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenuItem jMenuAjuSobre;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuItem jMenuCadAdm;
    public static javax.swing.JMenuItem jMenuCadCid;
    private javax.swing.JMenuItem jMenuCadCli;
    private javax.swing.JMenuItem jMenuCadCompra;
    public static javax.swing.JMenuItem jMenuCadContrato;
    private javax.swing.JMenuItem jMenuCadEquip;
    public static javax.swing.JMenuItem jMenuCadEstado;
    private javax.swing.JMenuItem jMenuCadForn;
    private javax.swing.JMenuItem jMenuCadOs;
    private javax.swing.JMenuItem jMenuCadOsAtendida;
    public static javax.swing.JMenuItem jMenuCadTipoServ;
    public static javax.swing.JMenuItem jMenuCadUsuario;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuOpSair;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JMenuItem jMenuRelEstCid;
    private javax.swing.JMenuItem jMenuRelServ;
    public static javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
