/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.ConnectionFactory;
import java.sql.*;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import model.dao.UsuarioDAO;
/**
 *
 * @author Pretinho
 */
public class FormLogin extends javax.swing.JFrame {
Connection conexao = null;
PreparedStatement stmt = null;
ResultSet rs = null;
    /**
     * Creates new form TelaLogin
     */
    public FormLogin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        btnAcessar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lbliconBanco = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/Login.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(310, 80, 180, 30);

        lblUsuario.setText("USUÁRIO:");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(250, 40, 60, 30);

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(310, 40, 180, 30);

        lblSenha.setText("SENHA:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(260, 80, 50, 30);

        btnAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login2.png"))); // NOI18N
        btnAcessar.setText("ACESSAR");
        btnAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarActionPerformed(evt);
            }
        });
        btnAcessar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAcessarKeyPressed(evt);
            }
        });
        getContentPane().add(btnAcessar);
        btnAcessar.setBounds(310, 120, 130, 40);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Consulta.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(410, 170, 90, 31);

        lbliconBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/No-Conection.png"))); // NOI18N
        getContentPane().add(lbliconBanco);
        lbliconBanco.setBounds(290, 170, 40, 40);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Login.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 260, 230);

        setSize(new java.awt.Dimension(511, 265));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarActionPerformed
        
        UsuarioDAO dao = new UsuarioDAO();
        
        /*A linha abaixo usa o get Password e por isso a classe wepper (new String)e o argumento seguinte entre parêntese
        */
        if (dao.checkLogin(txtUsuario.getText(), new String (txtSenha.getPassword()))){
            new Menu().setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Senha ou usuário inválidos");
        }
            
    }//GEN-LAST:event_btnAcessarActionPerformed
    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        
        if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){
           txtSenha.requestFocus();
       }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        
        if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){
           btnAcessar.requestFocus();
       }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void btnAcessarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAcessarKeyPressed
        
        if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){
//            
            UsuarioDAO dao = new UsuarioDAO();
            
        if (dao.checkLogin(txtUsuario.getText(), new String (txtSenha.getPassword()))){
            new Menu().setVisible(true);
            this.dispose();
        }else{
            txtUsuario.setText("");
            txtSenha.setText("");
            JOptionPane.showMessageDialog(null, "Senha ou usuário inválidos");
        }
       }
    }//GEN-LAST:event_btnAcessarKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        UsuarioDAO dao = new UsuarioDAO();
        
         if (!dao.checkConexao()){
             lbliconBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/No-Conection.png")));
             btnAcessar.setEnabled(false);
             txtUsuario.setEnabled(false);
             txtSenha.setEnabled(false);
             JOptionPane.showMessageDialog(null, "Falha: Banco de dados ou tabela usuário não acessível");
         }else{
             lbliconBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/conection-ok.png")));
         }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessar;
    private javax.swing.JButton btnSair;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lbliconBanco;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
